In [1]:
import numpy as np

 - You want to create a numpy array filled with random values between 0 - 1

In [6]:
array_rnd = np.random.random(size=(3, 4, 2))

In [7]:
array_rnd.shape

(3, 4, 2)

In [8]:
array_rnd.ndim

3

In [10]:
array_rnd

array([[[0.75543605, 0.42095234],
        [0.51709907, 0.12165064],
        [0.5541167 , 0.23243043],
        [0.94227545, 0.06252576]],

       [[0.97874145, 0.02642182],
        [0.09090636, 0.83637781],
        [0.85014456, 0.74821421],
        [0.52183751, 0.8682671 ]],

       [[0.39637747, 0.88640362],
        [0.45590118, 0.88646603],
        [0.69433755, 0.22625496],
        [0.04637812, 0.91234161]]])

 - create numpy array filled with constants

In [12]:
array_zeros = np.zeros(shape = (2, 3))

In [13]:
array_ones = np.ones(shape = (4, 3))

In [17]:
array_const = np.full(shape=(4, 2), fill_value=20)

 - Matrix Operations

In [18]:
# Transpose
array_1 = np.random.random((3, 4))

In [19]:
array_1

array([[0.31668661, 0.84781081, 0.6284157 , 0.48610955],
       [0.2631968 , 0.82454637, 0.36721207, 0.33143658],
       [0.51510058, 0.77402777, 0.67656937, 0.60801626]])

In [20]:
array_1.T

array([[0.31668661, 0.2631968 , 0.51510058],
       [0.84781081, 0.82454637, 0.77402777],
       [0.6284157 , 0.36721207, 0.67656937],
       [0.48610955, 0.33143658, 0.60801626]])

In [23]:
# Inverse of a Square Matrix => A*B = I
# Square Matrix => no. rows = no. columns

square_matrix = np.random.random(size=(4, 4))

In [24]:
square_matrix

array([[0.56625353, 0.83396431, 0.31769335, 0.54965384],
       [0.48999649, 0.25958587, 0.01516796, 0.15620919],
       [0.67454013, 0.63323915, 0.05379334, 0.28676294],
       [0.22065614, 0.90552576, 0.69887987, 0.19085075]])

In [32]:
identity_matrix = np.identity(4)

In [33]:
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
1 * 6

6

In [35]:
6 * 1/6

1.0

In [38]:
square_matrix

array([[0.56625353, 0.83396431, 0.31769335, 0.54965384],
       [0.48999649, 0.25958587, 0.01516796, 0.15620919],
       [0.67454013, 0.63323915, 0.05379334, 0.28676294],
       [0.22065614, 0.90552576, 0.69887987, 0.19085075]])

In [37]:
np.dot(identity_matrix, square_matrix)

array([[0.56625353, 0.83396431, 0.31769335, 0.54965384],
       [0.48999649, 0.25958587, 0.01516796, 0.15620919],
       [0.67454013, 0.63323915, 0.05379334, 0.28676294],
       [0.22065614, 0.90552576, 0.69887987, 0.19085075]])

In [40]:
inv_sq_matrix = np.linalg.inv(square_matrix)

In [41]:
np.dot(inv_sq_matrix, square_matrix)

array([[ 1.00000000e+00,  0.00000000e+00, -5.55111512e-17,
         1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
        -1.11022302e-16],
       [-4.44089210e-16,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00],
       [-1.66533454e-16,  2.22044605e-16,  2.22044605e-16,
         1.00000000e+00]])

In [43]:
det_square_matrix = np.linalg.det(square_matrix)

### Arithematic Operations numpy Arrays

 - array with scaler

In [44]:
array_2 = np.random.random((3, 2))

In [45]:
array_2

array([[0.51764361, 0.41822697],
       [0.41605916, 0.23091645],
       [0.32263804, 0.76101364]])

 - +, -, /, *, %

In [51]:
array_2 * 0.005

array([[0.00258822, 0.00209113],
       [0.0020803 , 0.00115458],
       [0.00161319, 0.00380507]])

 - array with another array

In [52]:
array_3 = np.array([1, 2])

In [55]:
array_3.shape, array_2.shape

((2,), (3, 2))

In [56]:
array_2 + array_3

array([[1.51764361, 2.41822697],
       [1.41605916, 2.23091645],
       [1.32263804, 2.76101364]])

In [59]:
array_4 = np.array([[1], [2], [3]])

In [61]:
array_4.shape

(3, 1)

In [62]:
array_2.shape

(3, 2)

In [64]:
array_2

array([[0.51764361, 0.41822697],
       [0.41605916, 0.23091645],
       [0.32263804, 0.76101364]])

In [65]:
array_4

array([[1],
       [2],
       [3]])

In [66]:
array_2 * array_4

array([[0.51764361, 0.41822697],
       [0.83211831, 0.4618329 ],
       [0.96791412, 2.28304093]])

 - when shapes match

In [67]:
array_5 = np.full((3, 2), 10)

In [68]:
array_5

array([[10, 10],
       [10, 10],
       [10, 10]])

In [69]:
array_2

array([[0.51764361, 0.41822697],
       [0.41605916, 0.23091645],
       [0.32263804, 0.76101364]])

In [71]:
array_2 * array_5

array([[5.17643614, 4.1822697 ],
       [4.16059156, 2.30916449],
       [3.22638039, 7.61013645]])

 - Matrix multiplication

In [73]:
array_6 = array_5.T

In [74]:
np.dot(array_2, array_6)

array([[ 9.35870584,  9.35870584,  9.35870584],
       [ 6.46975605,  6.46975605,  6.46975605],
       [10.83651684, 10.83651684, 10.83651684]])

In [75]:
np.random.randint(low=5, high=20, size=(3, 4))

array([[11,  6, 18, 10],
       [ 8, 11, 14, 19],
       [ 6,  9,  9, 17]])